env:
  global:
    - CC_TEST_REPORTER_ID=5460d8d46d6c882c0c1ca7fb2de4aa1a1fe0eb4c3db1b4529ed62b6581682d59
    - PG_URI=postgres://epilznyu:H1fy_z9mo8ibwHlQKPfiwIHf-IMlXihw@manny.db.elephantsql.com:5432/epilznyu
    - PG_HOST="manny.db.elephantsql.com"
    - PG_DB=epilznyu
    - PG_PASSWORD=H1fy_z9mo8ibwHlQKPfiwIHf-IMlXihw
    - PG_USER=epilznyu
language: node_js
node_js:
  - "stable"

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
 - npm run migrations

script: npm run coverage

cache:
  directories:
    - "node_modules"
after_success: 
 - npm run coveralls
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  app: questioner-andela
  on:
    repo: chikeozulumba/questioner-andela-bootcamp
    branch: develop
  api_key:
    secure: "cfea0c04-66ca-4bd9-982d-2cf139eddca2"